"""
Test script for spatial barrio validation.

Tests if points from geometry and geometry_val_s2 are within the correct barrio
by intersecting with basemaps/barrios_veredas.geojson.

Reads the gdf_geolocalizar.xlsx file that was generated by the pipeline
and displays statistics about the spatial validation columns.

Expected columns in output:
- geometry_distancias: "EN EL RANGO" or "FUERA DE RANGO" for original geometry
- geometry_val_s2_distancias: "EN EL RANGO" or "FUERA DE RANGO" for geocoded geometry
"""

import pandas as pd
import json
from pathlib import Path

def load_gdf_geolocalizar():
    """Load the gdf_geolocalizar dataset from the generated Excel file."""
    # Try both possible locations
    file_path_1 = Path(__file__).parent / 'app_outputs' / 'unidades_proyecto_outputs' / 'gdf_geolocalizar.xlsx'
    file_path_2 = Path(__file__).parent.parent / 'app_outputs' / 'unidades_proyecto_outputs' / 'gdf_geolocalizar.xlsx'
    
    if file_path_1.exists():
        file_path = file_path_1
    elif file_path_2.exists():
        file_path = file_path_2
    else:
        raise FileNotFoundError(f"File not found in either location:\n  {file_path_1}\n  {file_path_2}\nPlease run data_transformation_unidades_proyecto.py first to generate this file.")
    
    df = pd.read_excel(file_path)
    print(f"✓ Loaded {len(df)} records from {file_path}")
    return df

def test_spatial_validation():
    """Display statistics about the spatial validation columns in gdf_geolocalizar."""
    print("="*60)
    print("ANALYZING SPATIAL BARRIO VALIDATION RESULTS")
    print("="*60)
    
    # Load data
    df = load_gdf_geolocalizar()
    
    # Check if the spatial validation columns exist
    if 'geometry_distancias' not in df.columns or 'geometry_val_s2_distancias' not in df.columns:
        print("\n⚠️  Error: Spatial validation columns not found in the dataset!")
        print("   Expected columns: 'geometry_distancias', 'geometry_val_s2_distancias'")
        print("   Please ensure the pipeline has run with the latest code that generates these columns.")
        return None
    
    # Check geometry format
    print(f"\n🔍 Checking geometry format...")
    sample_geom = df[df['geometry'].notna()].iloc[0]['geometry'] if len(df[df['geometry'].notna()]) > 0 else None
    
    if sample_geom:
        if isinstance(sample_geom, dict):
            print(f"   ✓ geometry is dict object (correct format)")
            print(f"   Sample: {sample_geom}")
        elif isinstance(sample_geom, str):
            print(f"   ⚠️  geometry is string (converted by Excel)")
            print(f"   Sample: {sample_geom[:100]}...")
        else:
            print(f"   ⚠️  geometry has unexpected type: {type(sample_geom)}")
    
    # Report statistics
    print(f"\n{'='*60}")
    print("SPATIAL VALIDATION RESULTS FROM PIPELINE")
    print(f"{'='*60}")
    
    # Statistics for geometry
    geom_validations = df['geometry_distancias'].notna()
    geom_validation_count = geom_validations.sum()
    
    if geom_validation_count > 0:
        geom_en_rango = (df['geometry_distancias'] == 'EN EL RANGO').sum()
        geom_fuera_rango = (df['geometry_distancias'] == 'FUERA DE RANGO').sum()
        
        print(f"\n📊 Spatial validation for 'geometry' column:")
        print(f"   Total records: {len(df)}")
        print(f"   Total validations: {geom_validation_count}")
        print(f"   EN EL RANGO: {geom_en_rango} ({geom_en_rango/geom_validation_count*100:.1f}%)")
        print(f"   FUERA DE RANGO: {geom_fuera_rango} ({geom_fuera_rango/geom_validation_count*100:.1f}%)")
        print(f"   No validation: {len(df) - geom_validation_count}")
    else:
        print(f"\n⚠️  No spatial validations available for 'geometry' column")
    
    # Statistics for geometry_val_s2
    geom_s2_validations = df['geometry_val_s2_distancias'].notna()
    geom_s2_validation_count = geom_s2_validations.sum()
    
    if geom_s2_validation_count > 0:
        geom_s2_en_rango = (df['geometry_val_s2_distancias'] == 'EN EL RANGO').sum()
        geom_s2_fuera_rango = (df['geometry_val_s2_distancias'] == 'FUERA DE RANGO').sum()
        
        print(f"\n📊 Spatial validation for 'geometry_val_s2' column:")
        print(f"   Total records: {len(df)}")
        print(f"   Total validations: {geom_s2_validation_count}")
        print(f"   EN EL RANGO: {geom_s2_en_rango} ({geom_s2_en_rango/geom_s2_validation_count*100:.1f}%)")
        print(f"   FUERA DE RANGO: {geom_s2_fuera_rango} ({geom_s2_fuera_rango/geom_s2_validation_count*100:.1f}%)")
        print(f"   No validation: {len(df) - geom_s2_validation_count}")
    else:
        print(f"\n⚠️  No spatial validations available for 'geometry_val_s2' column")
    
    # Show examples of each category
    print(f"\n{'='*60}")
    print("EXAMPLES OF VALIDATION RESULTS")
    print(f"{'='*60}")
    
    # Examples for geometry column
    if geom_validation_count > 0 and geom_en_rango > 0:
        print(f"\n✓ Examples of geometry 'EN EL RANGO' (first 5):")
        en_rango_examples = df[df['geometry_distancias'] == 'EN EL RANGO'].head(5)
        for idx, row in en_rango_examples.iterrows():
            print(f"   {row['upid']}: {row['barrio_vereda_val_s3']}")
    
    if geom_validation_count > 0 and geom_fuera_rango > 0:
        print(f"\n✗ Examples of geometry 'FUERA DE RANGO' (first 5):")
        fuera_rango_examples = df[df['geometry_distancias'] == 'FUERA DE RANGO'].head(5)
        for idx, row in fuera_rango_examples.iterrows():
            print(f"   {row['upid']}: Expected {row['barrio_vereda_val_s3']}")
    
    # Examples for geometry_val_s2 column
    if geom_s2_validation_count > 0 and geom_s2_en_rango > 0:
        print(f"\n✓ Examples of geometry_val_s2 'EN EL RANGO' (first 5):")
        en_rango_s2_examples = df[df['geometry_val_s2_distancias'] == 'EN EL RANGO'].head(5)
        for idx, row in en_rango_s2_examples.iterrows():
            print(f"   {row['upid']}: {row['barrio_vereda_val_s3']}")
    
    if geom_s2_validation_count > 0 and geom_s2_fuera_rango > 0:
        print(f"\n✗ Examples of geometry_val_s2 'FUERA DE RANGO' (first 5):")
        fuera_rango_s2_examples = df[df['geometry_val_s2_distancias'] == 'FUERA DE RANGO'].head(5)
        for idx, row in fuera_rango_s2_examples.iterrows():
            print(f"   {row['upid']}: Expected {row['barrio_vereda_val_s3']}")
    
    # Display column names for verification
    print(f"\n{'='*60}")
    print("AVAILABLE COLUMNS IN GDF_GEOLOCALIZAR")
    print(f"{'='*60}")
    print(f"\nAll columns: {', '.join(df.columns.tolist())}")
    
    return df

if __name__ == "__main__":
    try:
        df_result = test_spatial_validation()
        print(f"\n{'='*60}")
        print("TEST COMPLETED SUCCESSFULLY")
        print(f"{'='*60}")
    except Exception as e:
        print(f"\n✗ Error during testing: {e}")
        import traceback
        traceback.print_exc()
